[BUGFIX] re #19075 - Hubspot - Disconnect company does not syncronize…
emgdev/hubspot-dotnet-sdk pull request #36
Opened 2021-07-02 12:00 UTC by annasandberg

… hubspot data

update Properties dictionary to not readonly
add tryParse to intConverter

This bug is about disconnect Company not setting customer card to null in hubspot. The issue was that Properties were not included in WCF contract and to be able to do that I had to make IReadOnlyDictionary to Dictionary. Property value had to be set as string in contract so in order to convert that back I had to add a tryParse to the IntTypeConverter.

2021-07-05 14:12 UTC, agnerh commented
@annasandberg Why do we need to change properties from `IReadOnlyDictionary` to `Dictionary` for the properties to be included in the WCF contract?

2021-07-16 14:18 UTC, Josephson199 commented
Have you tried adding below Data annotation to help WCF with serialization? 

 [KnownType(typeof(IReadOnlyDictionary<string, object>))]

2021-08-12 09:09 UTC, agnerh requested changes
I would like to know more about why we cant keep using `IReadOnlyDictionary` before we move on

2021-08-12 09:44 UTC, annasandberg commented
@agnerh  I realized I hadn't pulled the latest code when I made these changes and now I am having issues in HubSpotResourceService, looks like Renato have been exchanging a few classes and I am currently having problems registering those... So I am putting this as WIP for the moment until I have fixed those issues. I will then try again to get around the fact that the IReadOnlyDictionary did not work - I couldn't set the Properties value but right now I don't remember the exact error

2021-09-17 14:17 UTC, annasandberg commented
closing this since Henrik updated the sdk in another PR

2021-09-17 14:17 UTC, closed without merging